### ISSUE TITLE
support for scotty-0.20

### ISSUE THREAD

**Issue by jkachmar** [ku-fpg/kansas-comet#10]
## Description

[`scotty`](https://hackage.haskell.org/package/scotty) has been updated to [`0.20.0`](https://hackage.haskell.org/package/scotty-0.20/changelog).

**Comment by RyanGlScott** [comment]
I've uploaded [`kansas-comet-0.4.2`](https://hackage.haskell.org/package/kansas-comet-0.4.2) to Hackage with a fix.
